= Volet infrastructure
:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Sommaire

Dernière modification : {docdate}

== Introduction
Ceci est le point de vue infrastructure de l’application. Il décrit le déploiement des modules applicatifs dans leur environnement d'exécution cible et l'ensemble des dispositifs assurant leur bon fonctionnement.

Les autres volets du dossier sont accessibles link:./README.adoc[d'ici].

Le glossaire du projet est disponible link:glossaire.adoc[ici]. Nous ne redéfinirons pas ici les termes fonctionnels ou techniques utilisés.

=== Documentation de Référence

.Références documentaires développement
[cols="1,2,5,4"]
|====
|N°|Version|Titre/URL du document|Détail
|01|1.0.0|link:./cahier-des-charges.pdf[cahier des charges]|section 4.5 : Développement
|====

== Contraintes

=== Contraintes sur la disponibilité

==== MTTD

- l’hypervision se fait 24/7/365

==== Outils et normes de supervision

- Les batchs doivent pouvoir se lancer sur un endpoint REST

==== Interruptions programmées

- On estime l’interruption de chaque serveur à 5 mins par mois. Le taux de disponibilité effectif des serveurs en prenant en compte les interruptions programmées système est donc de 99.99 %.

=== Hébergement

- Cette solution sera hébergée chez OVH
