= Volet développement
:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Sommaire

Dernière modification : {docdate} 

Etat du document : 

== Introduction
Ceci est le point de vue développement de l’application. Il décrit le code à produire et comment l'écrire.

Les autres volets du dossier sont accessibles link:./README.adoc[d'ici].

=== Documentation de Référence

.Références documentaires développement
[cols="1,1,4,4"]
|====
|N°|Version|Titre/URL du document|Détail
|01|1.0.0|link:./cahier-des-charges.pdf[cahier des charges]|section 4.5 : Développement
|==== 

== Non statué

=== Points soumis à étude complémentaire

.Points soumis à étude complémentaire
[cols="1,6,1,1,1"]
|====
|ID|Détail|Statut|Porteur du sujet  | Échéance
|ED1|SEO |À DEFINIR|N/A  | N/A
|====

=== Hypothèses

.Hypothèses
[cols="1,4"]
|====
|ID|Détail


|====

== Contraintes

== Exigences non fonctionnelles

- Environnement de développement imposé par le donneur d'ordre : prestashop (solution open source)


=== Ergonomie

- Site web responsive avec JavaScript, HTML et CSS
 
=== Internationalisation (i18n)

- Le site proposera une interface en langue française et anglaise

=== Exigences de SEO

- Les pages statiques du site devront suivre les bonnes pratiques SEO pour optimiser sa visibilité. Le contenu textuel sera généré par php afin qu’il soit consultable par les moteurs de recherche. Pour avoir un référencement optimal sur les articles du site, il faut un title différent pour chaque page d’article.

- Gestion des META-TAGS par produit et par page de contenu

- Générer un Flux RSS de produits

- Gestion des liens sponsorisés sur devis

== Architecture cible

=== Pile logicielle

Environnement de développement imposé par le donneur d'ordre Solution open source : prestashop

Le prestataire devra réaliser le site dans l'environnement de développement suivant : 

- SGBD : mysql

- Environnement de développement (HTML, PHP, XML, etc.) : PHP
Pour arriver à notre but, il faudra utiliser différents langages de programmation : HTML, CSS, JavaScript, AJAX, PHP/SQL.

AJAX et JavaScript serviront à avoir des animations dans le site, entre les pages. PHP servira à générer les contenus texte dans le code source de la page, et SQL servira à la gestion de la base de données.

=== Versioning

- D’une façon générale, toute ressource non dérivée (source, outil, script de ci-cd, template, DDL de base de données, …​) doit être versionnée.

- La version logique globale du projet sera `x.y.z` (<majeur).<évolution>.<fix>)

=== Politique de gestion des commits

- Tous commit devrai respecter la norme de nommage Angular (link:https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#[AngularJS Git Commit Message Conventions])

=== Politique de gestion des branches

- La politique générale adoptée est la TBD (Trunk-Based Development)

- La branche principale est develop. Il s’agit d’une branche protégée vers laquelle il n’est pas possible pousser de commits.

- Tout commit devra faire l’objet d’une Merge Request avant intégration dans develop. Les critères de qualité (évalués de façon automatique lors de l’intégration continue) devront être atteints pour que le commit soit intégré.

- Chaque fonctionnalité, refactoring significatif ou bugfix sera donc réalisé sur une branche topic dédiée.

=== Fuseaux horaires

- Les heures ne seront jamais stockées sans fuseau horaire. En base, on utilisera des timestamps avec timezone (timestamptz) et en JS, des objets intégrant le fuseau horaire de façon explicite ou des epochs. La précision sera au moins de la milliseconde.

=== Provisionning et mises à jour des données

- Accès FTP au serveur via le logiciel FileZilla.